### PR TITLE
Update packages for 2.x

### PR DESCRIPTION
**Pull request by RobertIndie**
Update the package in 2.x

### CODE REVIEW

**Comment by Lanayx** [comment]
@RobertIndie Hi! Did you want to update nuget packages in examples?

**Comment by RobertIndie** [comment]
> @RobertIndie Hi! Did you want to update nuget packages in examples?

No. Actually, It would be better if we didn't have to touch the examples folder. I just want to upgrade the Pulsar.Client dependency.

However, I encountered the following error when running `dotnet restore` or `dotnet paket restore`:

```
Paket failed with
-> Error for /xxx/pulsar-client-dotnet/examples/FsharpExamples/paket.references: Package FSharp.Core was not found in group Examples of the paket.lock file.
```

So I removed the `FSharp.Core` from examples/FsharpExamples/paket.references.

But then I got this error when running `dotnet build`:

```
    /XXX/pulsar-client-dotnet/examples/FsharpExamples/FsharpExamples.fsproj : error NU1202: Package Pulsar.Client 3.6.2 is not compatible with net7.0 (.NETCoreApp,Version=v7.0). Package Pulsar.Client 3.6.2 supports: net8.0 (.NETCoreApp,Version=v8.0)
    /XXX/pulsar-client-dotnet/examples/CsharpExamples/CsharpExamples.csproj : error NU1202: Package Pulsar.Client 3.6.2 is not compatible with net7.0 (.NETCoreApp,Version=v7.0). Package Pulsar.Client 3.6.2 supports: net8.0 (.NETCoreApp,Version=v8.0)

```

It seems the example projects are still using the 3.x version. So, I added the package references to point to the correct Pulsar.Client package.

**Comment by Lanayx** [comment]
@RobertIndie I've fixed the paket issue, however, something in docker setup has changed and has to be fixed, it looks like init commands are not executed after container launch, for example I see this in action logs:
```
init-1  | bash: bin/wait-for-it-fixed.sh: /us/bin/env: bad interpreter: No such file or directory
```
I'm reluctant to merge it without first CI being fixed.

**Comment by RobertIndie** [comment]
> I've fixed the paket issue, however, something in docker setup has changed and has to be fixed, it looks like init commands are not executed after container launch, for example I see this in action logs:

Thanks for your fix. I have fixed the CI issue. PTAL

**Comment by Lanayx** [comment]
Thanks, published 2.17.0

**Pull request merged**
